### ISSUE TITLE
Sequences Scrollbar

### ISSUE THREAD

**Issue by whitesoup12** [whitesoup12/remote-falcon-tracker#103]
Show scroll bar on sequences tab.

**Comment by whitesoup12** [comment]
I can see there already is a scrollbar on the Sequences tab

**Comment by derwin12** [comment]
You know I went to another computer .. and I see it now too .. it was just light black on black and missed it.

![Screenshot from 2021-07-26 11-19-16](https://user-images.githubusercontent.com/4643499/127014605-eff39891-574a-4299-82c1-64017ecbb844.png)
