### ISSUE TITLE
UI seems incorrect for a song playing..

### ISSUE THREAD

**Issue by derwin12** [whitesoup12/remote-falcon-tracker#106]
So I have it set up in voting mode, the UI shows all the songs listed nicely with the votes to the right.
When a song is started and re-added back to the list, at the bottom, it shows in the wrong css format and hence looks "bad".

It adds it back in jukebox-list mode??

It does seem to be correct in that it wont let you choose the song since it is playing..

![2021-07-27 20_34_05-Remote Falcon - Brave](https://user-images.githubusercontent.com/4643499/127244862-a4438aa6-b089-407b-b37f-9560a73e09f2.jpg)

![2021-07-27 20_35_24-Remote Falcon - Brave](https://user-images.githubusercontent.com/4643499/127244929-f60aec31-91df-46d6-b167-6e68fd31506a.jpg)

**Comment by whitesoup12** [comment]
Fixed in 7.1.6.
