### ISSUE TITLE
Sequence Image URL's

### ISSUE THREAD

**Issue by Ryan-Ohio** [whitesoup12/remote-falcon-tracker#109]
When you place an URL for a Sequence, that image will populate for all songs below it that are blank.  So if I want say Ghostbusters image and I put it against song 1, but leave song 2 and 3 URL's blank, the ghostbusters image will show against all 3 songs.  Image attach where I used 2 urls and you can see how the images populated below for all non-url sequences.

Basically you need to put an image next to each sequence or it will copy down the image from the song above.

Hope that makes sense :)

Thanks James!!

![Sequence Image URL](https://user-images.githubusercontent.com/89036129/129603604-67013a1d-0960-4145-9cf4-a210973a2c96.JPG)

**Comment by whitesoup12** [comment]
Fixed in 7.1.9.
