### ISSUE TITLE
Installation of Plug-in Error

### ISSUE THREAD

**Issue by kevinkelly3** [whitesoup12/remote-falcon-tracker#117]
![image](https://user-images.githubusercontent.com/91383692/134777487-33f36abe-82fe-4a14-849a-c442d1c80c74.png)

**Comment by whitesoup12** [comment]
This looks to be an issue with FPP not being able to access GitHub. I believe there is a script in the Script Repository that can fix this.

**Comment by kevinkelly3** [comment]
I found the issue by searching the xLights Support group on Facebook. My DNS server was set to DHCP and was not accessing the internet to download the plug-in. I updated the DNS to point to my router IP address and then I was able to download the plugin. Thank you for the reply.
