### ISSUE TITLE
Audio on Viewer Gallery

### ISSUE THREAD

**Issue by Cassock** [whitesoup12/remote-falcon-tracker#119]
One of the viewer pages below seems to have some code to play audio, much to the chagrin of my wife as I was browsing them at 7am. I didn't download them to find out exactly which one, and it probably doesn't matter. I imagine some website voodoo would be in order to prevent it globally, yeah?
![image](https://user-images.githubusercontent.com/15901832/140748537-e40c8bba-c65c-4760-99a7-e07d38a8419c.png)

**Comment by whitesoup12** [comment]
Fixed. :)
