### ISSUE TITLE
Remote Playlist does not account for "Lead-In" commands

### ISSUE THREAD

**Issue by datcomputerguy** [whitesoup12/remote-falcon-tracker#123]
Currently the remote sequence indexing does not take into account lead-in items.
Simply increase the initial index by the length of the leadIn items?  Seems to have fixed my problems!

```
remote_falcon.php
Current Line 90:
...   $mainPlaylist = $response['mainPlaylist'];
...   $index = 1;

add   $leadIn = $response['leadIn']; //get the leadIn part of the response
add   $index = $index + count($leadIn); //add the size of the leadIn to index to offset index counts

...   foreach($mainPlaylist as $item) {
```

**Comment by datcomputerguy** [comment]
would also need to make a similar change in the command update_remote_playlist.php file

**Comment by whitesoup12** [comment]
Adding lead ins or lead outs to your RF playlist is not necessary. Sounds like you're using the same playlist in RF in your normal schedules show. You should have a separate playlist only for syncing with RF that is not used in any schedules.

**Comment by datcomputerguy** [comment]
I get that, but I have some "modes" that like basically override RF (hard to explain).  Adding the 2 lines of code would do nothing if you don't have lead in items, wouldn't effect other users.  would only do something if they had lead-in item for weird people like me lol.

**Comment by whitesoup12** [comment]
Okay. So I don't plan on adding or supporting lead in items in RF, but if it's something you feel comfortable modifying in your plugin for your own needs and it works for you, that's no problem. Going to close this one as a non issue though.
