### ISSUE TITLE
Wrong Songs Playing

### ISSUE THREAD

**Issue by HonScottHMcCoy** [whitesoup12/remote-falcon-tracker#128]
No idea if it's something I did or if it's a bug?

I have a simple playlist. When "USA National Anthem" is selected, it shows selected as the next request. However, it plays the sequence above it (A Christmas Monologue) instead of the correct song. Then the playlist continues. Rebooted, etc. Same results. (See included screenshots.)

I then selected Snowmiser-Heatmiser while it was playing Lit This Year. The Lit This Year sequence ended and then it played Lit This Year again immediately. 

It's like the selected sequences display properly in RF, but it's triggering the wrong sequences within FPP.

FPP v5.4.1 (v5.4 branch)
RF Plugin v6.2.1

![image](https://user-images.githubusercontent.com/33946864/144336779-90e8fa9a-ba19-4ab3-b10a-d5576a17fa0c.png)

**Comment by whitesoup12** [comment]
Try resyncing your playlist to RF from the FPP plugin and make sure your RF playlist has no lead in or lead out items.

**Comment by HonScottHMcCoy** [comment]
My playlist does have intro and outro. However, that's the main show playlist. Should I create a dedicated playlist with just the songs for the RF?

**Comment by whitesoup12** [comment]
Yes, you should. One playlist only for syncing to RF.

**Comment by HonScottHMcCoy** [comment]
Thank you! That solved it. Great product!
