### ISSUE TITLE
Wrong song plays with voting if sequence has lead-in items

### ISSUE THREAD

**Issue by stk21** [whitesoup12/remote-falcon-tracker#136]
Found an issue tonight.  I had voting turned on (this will likely effect Jukebox as well).

If the playlist you are using remote falcon has lead in items, the vote for the song will be off in index by the number of items in the lead in.

![image](https://user-images.githubusercontent.com/32824148/144695280-f73032f5-69b2-400b-a65e-d045f48bb1b5.png)

![image](https://user-images.githubusercontent.com/32824148/144695265-6dd68186-b859-4fd9-bebf-cf5f7abec5fd.png)

I had a lead-in of two items, and the wining song index 5 was the 5th song....  however with the lead-in items it was index 7, so two up the song played.

**Comment by whitesoup12** [comment]
You have to use a separate playlist just for syncing with Remote Falcon, and that playlist cannot have lead ins, lead outs, be set to random, or be used in any schedules.

**Comment by stk21** [comment]
Thanks.  I found that work around before I issues the bug report.  I guess my workaround is just the way to do it.
