### ISSUE TITLE
API documentation no longer accessible

### ISSUE THREAD

**Issue by adamcoulombe** [whitesoup12/remote-falcon-tracker#139]
When I follow the link [https://app.swaggerhub.com/apis/whitesoup12/RemoteFalcon/6.2.0-oas3](https://app.swaggerhub.com/apis/whitesoup12/RemoteFalcon/6.2.0-oas3) I get an error from swaggerhub and I am unable to look at any API docs.

I just want to see if there is a rest endpoint to play a specific song

**Comment by whitesoup12** [comment]
It definitely pulls up for me.

**Comment by adamcoulombe** [comment]
Yeah weird, It is working now I see. Was not working for a while there. Must have been a site error on swaggerhub. Sorry about that!
