### ISSUE TITLE
after-hours-message section of webpage is never displayed

### ISSUE THREAD

**Issue by abanchieri** [whitesoup12/remote-falcon-tracker#145]
Recently configured RF this for this season. All features work fine except that the after-hours message is never displayed.  This happens with the default webpage as well. I am running FPP v5.4.1 and have two playlists. The "Christmas" playlist runs on repeat from dusk to 10 PM and contains all the show sequences. The "Idle" playlist contains a single 5 min animation and runs on repeat from 10:05 PM to midnight.

**Comment by whitesoup12** [comment]
You have to turn Viewer Control off to display the after hours section

**Comment by abanchieri** [comment]
Thanks, that helps. Does it make sense to have "Remote Falcon - Turn Viewer Control On" as lead-in and "Remote Falcon - Turn Viewer Control Off" as lead-out for the "Christmas" playlist?

**Comment by whitesoup12** [comment]
You can do it that way or add the commands as a scheduled entry, which is actually the preferred way.

**Comment by abanchieri** [comment]
Thank you. Problem solved. Merry Christmas.
