### ISSUE TITLE
Error with web page forwarding

### ISSUE THREAD

**Issue by JoelDearing** [whitesoup12/remote-falcon-tracker#164]
Hello, I created saintnicks106.remotefalcon.com, and also purchased saintnicks106.com from namecheap.  I was able to enter the forwarding info successfully.  When I go to saintnicks1056.com I get Error code: SSL_ERROR_NO_CYPHER_OVERLAP.  Doing some poking around on namecheap they are telling me that a new SSL certificate is needed.  (I assume by you??) or perhaps a reissue.
These links  are why I am posting here.
https://www.namecheap.com/support/knowledgebase/article.aspx/811/70/how-do-i-reissue-my-ssl-certificate/
https://www.namecheap.com/support/knowledgebase/article.aspx/467/67/how-to-generate-csr-certificate-signing-request-code/
Thanks in advance.

**Comment by whitesoup12** [comment]
That SSL issue would be on your end. You need to be able to access your domain using https.

**Comment by whitesoup12** [comment]
Closing this as inactive.
