### ISSUE TITLE
BUG: Highest voted song doesn't play after PSA

### ISSUE THREAD

**Issue by chuckackerman** [whitesoup12/remote-falcon-tracker#168]
When a PSA is scheduled to play in voting mode it shows up in the voting list with 11111 votes putting it higher in the list than the top voted sequence.  And it is treated as the highest voted sequence. The PSA plays and the rest of the votes are cleared. Thus the highest voted sequence doesn't play since it had less votes than the PSA. FPP then returns to the normal playlist.

**Comment by whitesoup12** [comment]
The fix for this has been released. Made it so votes do not reset if the winning sequence is a PSA.

**Comment by chuckackerman** [comment]
Thanks so much for this.  I tested the best I know how this morning and it runs perfectly.
