### ISSUE TITLE
Incorrect song played when adding items before playlist

### ISSUE THREAD

**Issue by brianbarrell** [whitesoup12/remote-falcon-tracker#17]
![Capture](https://user-images.githubusercontent.com/52831201/96778285-0e995100-13b1-11eb-8275-be9e256dc7d8.JPG)

When you have items before the playlist as in the example photo I attached, The wrong song is selected.  If you choose for instance "Burl Ives - Holly Jolly Christmas", RF will choose the third item in the list - "Beach Boys - Little Saint Nick" instead of the correct song.  I assume it just counts down from the top and plays that item.  This unfortunately does not work for those of us with extra things in front of the sequences.  Hopefully there is a way to ignore lines before sequences, or for that matter between sequences.

**Comment by whitesoup12** [comment]
@brianbarrell, is the playlist pictured above the one that is synced with RF? If so, you need to create a separate playlist that has no lead in or lead out items and sync that one with RF instead.

**Comment by whitesoup12** [comment]
@brianbarrell, were you able to get this resolved?

**Comment by whitesoup12** [comment]
Closing as invalid.
