### ISSUE TITLE
Next Selection Incorrect When Playlist Randomized

### ISSUE THREAD

**Issue by cmichaelhansen** [whitesoup12/remote-falcon-tracker#172]
Hello!

I noticed a small issue today in my displays remote viewer page for the song listed in the "Next Selection". It seems to be pulling from the playlist order vs. the order used in the status page. In the status page, the playlist I have is randomized each playthrough and shows the correct "Next Song" but the remote viewer page displays incorrectly (however it's correct if the playlist wasn't random, it shows the song immediately after). I've attached some screenshots to illustrate.

Current Playing Song + The Index/Status Page
![image](https://user-images.githubusercontent.com/1878012/204682758-8634cc29-29c0-466b-b81a-ac361d86cee8.png)

Current Playing Song + The Playlist page (selecting the current playing playlist)
![image](https://user-images.githubusercontent.com/1878012/204682910-7ef72ac7-5f4a-4866-a7f9-9af4a0a0a139.png)

Here is the section in my page for reference:
![image](https://user-images.githubusercontent.com/1878012/204683372-cfc692e6-d733-4643-b058-49191dc67823.png)

**Comment by whitesoup12** [comment]
Yeah, if you use random, next up won’t work. There’s currently no API to
get next sequence in a playlist, so using the playlist order is all I’m
able to do.

**Comment by cmichaelhansen** [comment]
That's odd, I could have sworn it was working earlier this week and it has always been set to randomize each play through. The only change I made was to remove a sequence from the main playlist. I hadn't made any updates to that playlist since last season. If you pick a song via Jukebox mode, it does properly show that song will be next.

**Comment by whitesoup12** [comment]
Random playlists have actually always been an issue. It was something that
was even brought up last year, but there’s just no fix for it at this time.

**Comment by cmichaelhansen** [comment]
Maybe it was wishful thinking on my part. I found this after I was done with my show last year and wanted to utilize it this go 'round. I'll update my template accordingly. Thanks for the awesome plugin and hosting the sites!
