### ISSUE TITLE
Requested song playing wrong song

### ISSUE THREAD

**Issue by iamwally** [whitesoup12/remote-falcon-tracker#19]
I added a sequence to my Remote Falcon playlist and resynced but when I requested the new song be played I got a totally different song to play from Remote Falcon playlist.

**Comment by whitesoup12** [comment]
@iamwally can I get more info on this? Tried replicating and I can't. I synced a playlist, added a new item, then resynced, and everything plays that should play.

**Comment by chassy33** [comment]
@whitesoup12 not sure if this is the same issue, but I am also having this problem. I have 2 playlists. Halloween and halloween_RF. Halloween plays every night. Halloween_RF syncs with RF. Both playlists are identical. Whatever is selected in RF the previous song will play. For example, if song 3 is voted and wins, song 2 plays. This happens every time.

**Comment by whitesoup12** [comment]
@chassy33 can you paste a screenshot of your Halloween_RF playlist?

**Comment by chassy33** [comment]
@whitesoup12 I figured it out. My issue was I have Lead In and Lead out scripts in my playlist. once I deleted those from my RF playlist, it plays them just as it should!
