### ISSUE TITLE
Better checks for jukebox requests

### ISSUE THREAD

**Issue by whitesoup12** [whitesoup12/remote-falcon-tracker#22]
Need to ensure jukebox checks are happening later in the queue.

**Comment by friskybri** [comment]
I think what you are saying is jukebox only checks the current and next song.  So if someone kept adding a song over and over they could.   Jukebox should check he queue to see if its already queued up.   I am having that issue where several people will request the same song and it plays like every other song.   If it would check the entire queue that would be nice from multiple copies of a song queued up.
