### ISSUE TITLE
Jukebox checking the entire queue to see if that song is added

### ISSUE THREAD

**Issue by friskybri** [whitesoup12/remote-falcon-tracker#23]
Issue I see is in Jukebox you can add the same song over and over.  Right now jukebox checks the current and next song.  After that there is no way to stop someone from adding song 1 then song 2 then back to song1 over and over.   If someone wants to sabotage your show this is it.   Also instead of saying playlist full it should say song already requested in queue.

**Comment by whitesoup12** [comment]
Will track this issue in #22
