### ISSUE TITLE
sequences list not updating (using xSchedule 2020.46)

### ISSUE THREAD

**Issue by plalande** [whitesoup12/remote-falcon-tracker#25]
site:
https://lumiereplacebellevue.remotefalcon.com

im including a screenshot of xSchedule
I changed the sequence list in xSchedule but the list does not update in RF

![xlights](https://user-images.githubusercontent.com/73859953/97932568-579cbe00-1d3e-11eb-856b-726938366e80.png)

**Comment by whitesoup12** [comment]
@plalande did you add your remote token to the plugin?

**Comment by plalande** [comment]
unless it changed I did when I first when I created my account

**Comment by whitesoup12** [comment]
Maybe try adding it again to the plugin. Usually that 502 is due to an invalid token.

**Comment by plalande** [comment]
where do I find the token

**Comment by whitesoup12** [comment]
On your Remote Falcon control panel, click the “Here are the steps” link in the header below the navigation bar. Your remote token is in there.

**Comment by plalande** [comment]
ok I added the token, but still the old list in RF 
![xlights2](https://user-images.githubusercontent.com/73859953/97933686-72bcfd00-1d41-11eb-977e-acd2fe267dd8.png)

**Comment by whitesoup12** [comment]
Even after a hard refresh? Ctrl (or Cmd)+Shift+R

**Comment by plalande** [comment]
I tried the hard reset in the visitors and admin sites

**Comment by whitesoup12** [comment]
Okay. I’ll dig more into it.

**Comment by keithsw1111** [comment]
I would need to see your .xschedule file and xSchedule log file to work out why this is happening.

**Comment by plalande** [comment]
Fetching current playing mode ...
{"viewerControlMode":"voting","remoteSubdomain":"lumiereplacebellevue","interruptSchedule":true}
MODE: voting
SUBDOMAIN: lumiereplacebellevue
Started.
Uploading playlist to Remote Falcon.
    {"message":"Success"}
Clearing remote falcon list of songs.
    <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>

    <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>

    <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>

    <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>

    <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>

    <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>

    <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>

    <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>

    <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>

    <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>

    {"message":"Queue Empty"}
Updating remote falcon with the playing song: XATW Into the Unknown
{"currentPlaylist":"XATW Into the Unknown"}
Updating remote falcon with the playing song: null
{"currentPlaylist":"null"}
[xlights.zip](https://github.com/whitesoup12/remote-falcon-tracker/files/5478766/xlights.zip)

**Comment by keithsw1111** [comment]
That is not the xSchedule log.

**Comment by plalande** [comment]
here you go 
[xSchedule_l4cpp.log](https://github.com/whitesoup12/remote-falcon-tracker/files/5478824/xSchedule_l4cpp.log)

but in the plugin if I click tools and view log I get error (unable to show log file)

**Comment by plalande** [comment]
please confirm you have the info you need

**Comment by keithsw1111** [comment]
trawling through the log I can see multiple uploads of the playlist and when i take that message and send it myself it works fine. I would need more information from james on exactly what was null because i am not seeing it in the xSchedule logs.

**Comment by whitesoup12** [comment]
In one of the screenshots the current playing sequence being sent showed null. Wasn’t sure if it was related to the playlist not syncing.

**Comment by plalande** [comment]
in all cases in RF viewer page shows the right sequence playing. Just the list include sequence that are no longer in my 2020 playlist.

When I press stop all in xSchedule I get this in RF
{"currentPlaylist":"XATW Into the Unknown"}
Updating remote falcon with the playing song: null
{"currentPlaylist":"null"}

**Comment by keithsw1111** [comment]
So what i think is happening here is there is a playlist scheduled on xSchedule which has finished but the scheduled time has not finished. So the current step is not valid which leads to a null being sent. I can change it to a blank but it is still possible rf will have an issue with that. The reason no one else sees this is i imagine this is a pretty uncommon situation. I have made that change for .47.

**Comment by whitesoup12** [comment]
@keithsw1111 that sounds fine from the RF side. I send a blank string from FPP when there is nothing playing as well. As for the playlists not syncing, I’ll dig some more on my end.

**Comment by plalande** [comment]
hello did you find the issue

**Comment by keithsw1111** [comment]
i am not sure. There will be a change in .47 for you to try.

**Comment by plalande** [comment]
great, thanks any idea when it will be out

**Comment by whitesoup12** [comment]
@plalande turns out the sequences are not syncing because of the diacritical marks in your sequence names. I'm looking into a fix for this.

**Comment by whitesoup12** [comment]
Diacritics are inserting properly.
