### ISSUE TITLE
Add "Not Playing" message

### ISSUE THREAD

**Issue by computergeek1507** [whitesoup12/remote-falcon-tracker#44]
Change {NOW_PLAYING} html tag to a default message like "Not Playing" or similar when no song is playing.

**Comment by whitesoup12** [comment]
Not sure I see the benefit in this since the viewer would already know nothing is playing. Showing nothing there I think makes more sense.

**Comment by brennja** [comment]
I would like RF to show "Holiday show hours message or something similar" when nothing is Playing.

**Comment by whitesoup12** [comment]
@brennja you can do that now. Download the default template and you'll see a section called "after-hours" that display when viewer control is turned off.
