### ISSUE TITLE
Enhancement: Allow a ui option to use without a scheduled sequence.

### ISSUE THREAD

**Issue by CaffeinatedFunctionality** [whitesoup12/remote-falcon-tracker#45]
I allow my viewers to watch the show at any time via a button press. This button press will start a playlist. I would like this to work with remote falcon, in that, as long as any playlist is playing it will allow the ability to use remote falcon to choose a song. If needed I probably can put in a PR for this if there you allow PRs for the site

**Comment by whitesoup12** [comment]
@CaffeinatedFunctionality, not sure I follow. RF will work as long as an active schedule is running. The schedule doesn't even need to have any sequences or media in it. It could be a 5 second repeating pause and RF would still pull in requests.
