### ISSUE TITLE
Shows Playing when nothing is playing

### ISSUE THREAD

**Issue by brennja** [whitesoup12/remote-falcon-tracker#46]
Change to new HTML format yesterday.
Playing Now - shows Billie Ellish, but nothing is actual playing.
No schedule running
Reset votes does not clear it
Sync playlist does not clear it

**Comment by whitesoup12** [comment]
@brennja are you using xSchedule or FPP?

**Comment by brennja** [comment]
FPP

**Comment by whitesoup12** [comment]
What's your show name? FPP should remove the Now Playing once the schedule is done.

**Comment by brennja** [comment]
ForestLightShow

**Comment by whitesoup12** [comment]
I went ahead and cleared it out for you. I'll check the plugin an make sure it's clearing the song when it should.
