### ISSUE TITLE
Error to install plugin

### ISSUE THREAD

**Issue by spankurmonkey** [whitesoup12/remote-falcon-tracker#50]
I first attempted to install on the current version of FPP, which I don't recall.

I got this message :  

```
Installing plugin remote-falcon
Cloning into 'remote-falcon'...
fatal: unable to access 'https://github.com/whitesoup12/remote-falcon-plugin.git/': Could not resolve host: github.com
chown: cannot access 'remote-falcon': No such file or directory

Done

```
I then checked to see if I can upgrade FPP and had an error with that and after checking I had the DNS set wrong.   
I corrected it and then did the FPP upgrade to v4.5.1

Afterwards, after rebooting I went back to do the Remote Falcon plugin and got the same message again:

```
Installing plugin remote-falcon
Cloning into 'remote-falcon'...
fatal: unable to access 'https://github.com/whitesoup12/remote-falcon-plugin.git/': Could not resolve host: github.com
chown: cannot access 'remote-falcon': No such file or directory

Done
```

**Comment by whitesoup12** [comment]
This would be an issue with your FPP not able to access the internet.

**Comment by spankurmonkey** [comment]
how could that be when I just did a FPP upgrade to v4.5.1 -- that requires internet if I am not mistaken.

**Comment by whitesoup12** [comment]
Simple check would be to go to the Script Repository. If nothing shows up, it’s an internet issue.
