### ISSUE TITLE
Next shows nothing

### ISSUE THREAD

**Issue by spankurmonkey** [whitesoup12/remote-falcon-tracker#51]
Set to Jukebox  --- 

Whats Playing now shows but the next does not.

Does next mean next in the defined playlist or something else?

Here is the code from the page 

<div {jukebox-dynamic-container}>
    <p class="rf-titles">-What's Playing Next-</p>
    <div style="text-align: center; color: white; font-size: 20px;">
        {NEXT_PLAYLIST}
    </div>
    <p class="rf-titles">-Songs in Queue-</p>
    <div style="text-align: center; color: white;font-size: 20px;">
        {QUEUE_SIZE}
    </div>
    
</div>

**Comment by whitesoup12** [comment]
Next up only shows the next request. Not anything from the scheduled show.
