### ISSUE TITLE
after-hours-message

### ISSUE THREAD

**Issue by spankurmonkey** [whitesoup12/remote-falcon-tracker#54]
after-hours-message

says - will display a message if your show isn't playing a scheduled playlist.

using the default template on my site this section does not print at all - my show is not running any playlist.

```
<!-- This section will display a message if your show isn't
playing a scheduled playlist-->

<div {after-hours-message}>
    <div class="after-hours">
        Our show hours are <br />
        Sunday through Thursday from Sunset to 10:00 P.M.
        Friday and Saturday from sunset to 11:00 P.M.
    </div>
</div>
```

**Comment by whitesoup12** [comment]
Viewer control also has to be turned off. You can turn it off manually in the Remote falcon control panel or via the viewe_control_on and viewer_control_off scripts if using FPP.

**Comment by spankurmonkey** [comment]
In the script repository?  I am not finding it.

**Comment by spankurmonkey** [comment]
I also notice if I turn of manually it shows the after hours but then it still shows "playing now"

**Comment by whitesoup12** [comment]
> I also notice if I turn of manually it shows the after hours but then it still shows "playing now"
You'll need to double check your viewer page HTML and make sure the "Now Playing" section is inside the dynamic div section. The default template is correct if you need to reference it.

> In the script repository? I am not finding it.
When you go to the Remote Falcon plugin, the control scripts get copied over to the Scripts tab in the File Manager.

**Comment by spankurmonkey** [comment]
![Image 3](https://user-images.githubusercontent.com/17863712/100645653-981e3600-3302-11eb-93b5-67e962942403.jpg)
what are the parameters for this?   meaning turn it on an off - never used any of these FPP features.

**Comment by whitesoup12** [comment]
So you would actually add these scripts to the Lead In and Lead Out sections of your playlist. For example, the playlist that runs at the start of your show, you would add the on script as a lead in. Then whatever playlist plays at the end your show, you would add the off script as a lead out. Just select Script from the type dropdown, select the proper script, then drag it to the lead in or lead out.

**Comment by spankurmonkey** [comment]
Got it thanks... I just realized now there was a FB group for this... sorry for posting this here.

**Comment by whitesoup12** [comment]
No worries. :)

**Comment by spankurmonkey** [comment]
Hey, one thing... I got the scripts working as you said.  but I did mention that when its turned to the off mode, the viewer page still says "Playing Now" -

Shouldn't that not show when it's in the off mode?

**Comment by whitesoup12** [comment]
@spankurmonkey looks like that is an issue in the default template as well. You can easily move the Now Playing section into the {jukebox-dynamic-container} div and/or the {playlist-voting-dynamic-container} div.
