### ISSUE TITLE
Admin Control page!

### ISSUE THREAD

**Issue by NFAZ10** [whitesoup12/remote-falcon-tracker#59]
Would love an admin control page that can change brightness,vol, trigger my playlists similar to jukebox without messing with the stats of my page!

**Comment by Cassock** [comment]
FPP does all of this already without messing with any stats. I'd argue this is redundant and probably out of scope of the project.

**Comment by whitesoup12** [comment]
Not likely something that will be added. Easiest way to do this is with Dataplicity set up on FPP to access it from anywhere.
