### ISSUE TITLE
Cannot get next item to play when spaces in playlist name

### ISSUE THREAD

**Issue by bshep** [whitesoup12/remote-falcon-tracker#6]
I had posted the issue on the project page before i realized this was the correct place: https://github.com/whitesoup12/remote-falcon-plugin/issues/27#issue-723877165

I dont want to copy past the whole thing, but in essence: If the synced playlist (the one selected in the remote falcon plugin configuration page) has a space in the name, the plugin is unable to get the next item to play and essentially gets stuck.

**Comment by whitesoup12** [comment]
Transferred original issue from the plugin repo and marked this as duplicate.
Please reference issue #7.
