### ISSUE TITLE
Donate/Paid option removes Google adservices

### ISSUE THREAD

**Issue by zineer** [whitesoup12/remote-falcon-tracker#62]
Would be nice to have an option to remove the Google Ads code from the pages. Understand the reason for them, so maybe have them removed/option to hide based on a paid service and/or after donating.

**Comment by whitesoup12** [comment]
@zineer where do you see Google Ads? There are no ads anywhere on Remote Falcon.

**Comment by zineer** [comment]
@whitesoup12 No ads being shown, but the ads JS is being loaded:
![image](https://user-images.githubusercontent.com/583705/100911341-f1fa3980-3483-11eb-840c-ab2b55a498d6.png)

which pulls in a ton of other resources when run:
![image](https://user-images.githubusercontent.com/583705/100911481-25d55f00-3484-11eb-840d-6c8f1b5bb54a.png)

**Comment by whitesoup12** [comment]
Gotcha. That was added a while back when I was considering having ads in the Control Panel. But I abandoned the idea and just didn't remove the tag. I'll do this is part of cleanup for next year.

**Comment by whitesoup12** [comment]
@zineer, this is removed now.

**Comment by zineer** [comment]
Awesome, thanks!!
