### ISSUE TITLE
New account - Didn't get v2 template on Download Current

### ISSUE THREAD

**Issue by zineer** [whitesoup12/remote-falcon-tracker#63]
Signed up today, and downloaded the "Current Viewer Page", and it was the v1 template, which I set about modifying. Was confused at some of the things in the Facebook group not matching, so did a "Download Default Viewer Page" and was happily surprised to get a v2 template that was much nicer to modify! New accounts should probably get the v2 template by default as it is much nicer to work with, but either way it was odd that "download current" and "download default" didn't give the same page even though I hadn't modified anything.

**Comment by whitesoup12** [comment]
Nice catch. This has been fixed.
