### ISSUE TITLE
Can’t get sequences into remote falcon

### ISSUE THREAD

**Issue by wvpt** [whitesoup12/remote-falcon-tracker#64]
I am having problems getting my sequences to pull over from FPP to remote falcon. I have uninstalled and reinstalled plug-in a couple times. I copy the code and choose the dedicated playlist and click sync. It says sync was successful but nothing is there. Any ideas of something else to try? When I click on the sequences button on remote falcon nothing is there. Wamsleyfamilylights is my account.

**Comment by whitesoup12** [comment]
@wvpt, do any of your sequence names have special characters?

**Comment by wvpt** [comment]
Do special characters in any sequences. I created two separate playlists that are the same. One to sync in remote falcon and one to play in the scheduler. On my remote falcon page it is not showing what song is playing now and what is up either. I tried another viewer page and it still did not work. Any other suggestions?

**Comment by whitesoup12** [comment]
@wvpt do you have an active schedule running when you're testing?

**Comment by wvpt** [comment]
Yes I do

**Comment by whitesoup12** [comment]
What's your show name? I'll take a look at it.

**Comment by whitesoup12** [comment]
@wvpt can I get a screenshot of the playlist you're syncing with RF? And do you get a success message when you sync from FPP?

**Comment by wvpt** [comment]
Yes I do get a success message when I sync. I will send screenshots. 

https://wamsleyfamilylights.remotefalcon.com

**Comment by wvpt** [comment]
![Screen Shot 2020-12-04 at 1 29 50 PM](https://user-images.githubusercontent.com/54814143/101200872-e39f4f80-3634-11eb-9830-03c6fb6f383e.png)

**Comment by wvpt** [comment]
I have my scheduled sequence currently playing in case that helps when you look at it.

**Comment by whitesoup12** [comment]
Can you verify your remote token is correct and try syncing again and making note of the time you do it? Going to check the logs.

**Comment by wvpt** [comment]
Just verified and performed a sync. 135pm est

**Comment by whitesoup12** [comment]
This is a weird one. And you're running version 5.1.4 of the plugin? What version FPP do you have?

**Comment by wvpt** [comment]
Not sure how to tell version of plugin
![Screen Shot 2020-12-04 at 2 25 16 PM](https://user-images.githubusercontent.com/54814143/101206069-9a52fe00-363c-11eb-88e8-32d1fb8f8876.png)
![Screen Shot 2020-12-04 at 2 25 09 PM](https://user-images.githubusercontent.com/54814143/101206078-9de68500-363c-11eb-8929-673b733baee8.png)

**Comment by whitesoup12** [comment]
It's on the plugin page at the very top.

**Comment by wvpt** [comment]
version 5.1.4

**Comment by whitesoup12** [comment]
Can you try syncing a different test playlist? Just to see if that works?

**Comment by wvpt** [comment]
I created a new playlist with 1 song. Got the success message with clicked sync. Still does not show up on sequences tab on remote falcon.

**Comment by whitesoup12** [comment]
Can you download this script and add it your you Scripts folder then click run? I'd like to see what the output is. It's almost as if a blank request is getting sent to RF.  https://docs.google.com/document/d/1CrxDqxaALeCxZvLQAOwBlDvaxRq_Plwx9sCaNTnP5TY/edit?usp=sharing

**Comment by wvpt** [comment]
![Screen Shot 2020-12-04 at 3 30 13 PM](https://user-images.githubusercontent.com/54814143/101211731-a2636b80-3645-11eb-8048-57ff4d0b92ca.png)

**Comment by whitesoup12** [comment]
If you view the script, is the playlist name correct ("http://127.0.0.1/api/playlist/M1ChristmasRF")? Something is preventing the FPP API from getting your playlists.

**Comment by wvpt** [comment]
yes playlist is the same name.

**Comment by wvpt** [comment]
does it matter if the music file names have special characters?

**Comment by whitesoup12** [comment]
If you can change those you might try it.

**Comment by wvpt** [comment]
I edited playlists and only put 1 sequence in them and changes the file names to no spaces or special characters. Still same result. Result of running script is the same.

**Comment by whitesoup12** [comment]
Are you in the FPP group on Facebook? This might need to be a question for Dan Kulp.

**Comment by whitesoup12** [comment]
You may also try checking the apache2-error and apache2-base-error logs after running that script to see if there's an error somewhere.

**Comment by wvpt** [comment]
base error log has this error

[Sat Dec 05 00:24:13.759940 2020] [php7:notice] [pid 17285] [client 192.168.2.125:57583] getMediaDurationInfo:: Could not find media file - 01 - Christmas Every Day.mp3, referer: http://192.168.2.2/
[Sat Dec 05 00:24:22.439622 2020] [php7:notice] [pid 17131] [client 192.168.2.125:57587] getMediaDurationInfo:: Could not find media file - 01 - Christmas Every Day.mp3, referer: http://192.168.2.2/playlists.php

does that mean anything to you?

**Comment by wvpt** [comment]
PHP Warning:  file_get_contents(http://127.0.0.1/api/playlist/M1ChristmasRF): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized
 in /home/fpp/media/scripts/playlistTest.php on line 9

does that mean anything to you?

**Comment by whitesoup12** [comment]
Do you UI password enabled?

**Comment by wvpt** [comment]
no
