### ISSUE TITLE
PSA multiple play issue

### ISSUE THREAD

**Issue by plainfieldlights** [whitesoup12/remote-falcon-tracker#65]
When the normal playlist is going and you have a break (PSA) scheduled if someone votes for a song before the break then 2 other people vote for other songs then RF will play the PSA after the 3rd vote per the settings and then return the to the normal playlist and play the PSA again.  I also had an issue where RF kept playing the PSA over and over throughout the night.

**Comment by whitesoup12** [comment]
Double checked the logic behind the PSA for voting, and it's not actually checking individual votes. It checks the voting rounds. So if you have the PSA frequency set to 3, it should insert and play the PSA after 3 voting rounds. It is still possible for the PSA to come up during the normal schedule after it's already been played by RF. Going to mark this as a bug currently while I look into the PSA repeating constantly.
