### ISSUE TITLE
FPP Does Not Play Next Requested Song

### ISSUE THREAD

**Issue by jnietzer** [whitesoup12/remote-falcon-tracker#66]
I had this plugin working earlier in the day. I just started adding this to my show yesterday and in initial testing it all functioned as expected.

My goal is to allow remote falcon to work at the end of my regularly scheduled show for a couple hours so those who visit later can just pick a song and watch it as to not make too much after hours traffic. In order to implement this, I tried to use the scripts to start the remote falcon plugin at the beginning of a basic after hours playlist. However, after I ran the script to allow viewer control, I have not been able to get my FPP to receive requests from remote falcon. 

Looking at the logs, FPP had been checking 10 seconds before the end of a sequence for a remote falcon request. After I called the script, it no longer checks for sequence requests. I do not know if this is a bug or somewhere I implemented something incorrectly. However, at this time, no matter what settings I use I am not able to get remote falcon to receive requests and play the song. I can provide logs or additional information if that would be helpful.

**Comment by jnietzer** [comment]
[Log Files](https://fbcsp-my.sharepoint.com/:u:/g/personal/jnietzer_fbcsp_onmicrosoft_com/EW9JVEsBtERBg_GbfQcooYwBKHiCECqeFqITdWZspKqsTA?e=bkH7Ag)

I uploaded my log files for FPP if this helps. The most noted lines seem to include this: 
Dec  3 22:36:01 FPP-K32 fppd_boot_post[5668]: PHP Warning:  file_get_contents(https://remotefalcon.com/remotefalcon/api/updateWhatsPlaying): failed to open stream: HTTP request failed! HTTP/1.1 502 Bad Gateway
Dec  3 22:36:01 FPP-K32 fppd_boot_post[5668]:  in /home/fpp/media/plugins/remote-falcon/remote_fpp.php on line 195.

**Comment by jnietzer** [comment]
After playing around a little more, I realize that I can get it to work when I have a schedule running rather than just playing through a playlist. Looking through the wiki, it seems like this is the desired function. The odd part is that during testing, I was just running a playlist (not through the schedule) and remote falcon would cut in and play songs. So this ended up either being a bug report in initially allowing the remote falcon plugin to work when just running a playlist not in a schedule and/or a feature request to allow remote falcon to be tested by just running a playlist not in a schedule.

**Comment by whitesoup12** [comment]
RF now works without a scheduled playlist running
