### ISSUE TITLE
Feature Request: per-sequence commands

### ISSUE THREAD

**Issue by jgarvas** [whitesoup12/remote-falcon-tracker#82]
In the typical playlist builder you can put commands around a sequence.  In my show I am using SmartThings to turn on/off an AC nativity prop.

If someone chooses the two songs that require that nativity in RF it just plays the sequence.  It skips the logic that turns that AC prop on and off around the sequence.   Also, if someone requests a song and one of the nativity songs is playing, RF steals control away from FPP before the prop is shut off by the FPP command that shuts off the prop, leaving the nativity lit until the scheduler eventually plays through a nativity song and gets to the off command.

**Comment by whitesoup12** [comment]
This is possible now with commands and grouping.
