### ISSUE TITLE
Current location shows just a ","

### ISSUE THREAD

**Issue by ioscanner** [whitesoup12/remote-falcon-tracker#83]
Current location just shows a ","  So location doesn't work.  I have no text box or way to set the location.  It shows saved location is correct, but the current doesn't seem to work and doesn't allow it to be set.

**Comment by whitesoup12** [comment]
Try a hard refresh (Ctrl+Shift+R). I've noticed this as well and need to find a fix, but it's kind of random. Also noticed it shows up after several seconds sometimes.

**Comment by ioscanner** [comment]
I tried that.  I even cleared the cache.  I have tried on Safari, Chrome, MacOS and windows.  I can't seem to get the text box to return.

**Comment by ioscanner** [comment]
Ah I figured it out.  It seems it requires location to be pulled from the browser.  I don't allow that.  so I had to enable it for the site. Then the text box appears.

**Comment by ioscanner** [comment]
Hmm it seems the browser still tells me invalid location.  I even verified that the browser is passing the location to the website.     The site has the correct location.  My browser is showing the same location.  Is there a known issues with this not working?

**Comment by ioscanner** [comment]
Ok I got it.  iOS defaults are to block.  Everything seems to work now.
