### ISSUE TITLE
Allow mapping of more attributes to a sequence (ex Artist, Sequence length in time)

### ISSUE THREAD

**Issue by elou4042** [whitesoup12/remote-falcon-tracker#89]
Currently you can map Sequence Display Names in the "sequences" tab in the control panel.  This request is to also be able to add artist and track length to be mapped in the playlist variables.

Thank you, your work is greatly appreciated!

**Comment by whitesoup12** [comment]
This would probably be easiest if the artist, track name, and track length are just added to the display name. You can get all the info in there without having to make separate fields for those values.
