### ISSUE TITLE
Request for override

### ISSUE THREAD

**Issue by BulbsOnBenito** [whitesoup12/remote-falcon-tracker#90]
I would like to request an override option for the owner logged in on a device into remote falcon to be able to enter a customizable pin and be able to have the song they choose next play.

**Comment by whitesoup12** [comment]
Duplicate of #20

**Comment by BulbsOnBenito** [comment]
wait you did it?!? YAY

Darren Johnson

**Comment by whitesoup12** [comment]
lol, no. Was just noting that this request is a duplicate of (or similar to) another request. Still need to work on this one.

**Comment by BulbsOnBenito** [comment]
ok lol thank you! i’m excited still

Darren Johnson

**Comment by BulbsOnBenito** [comment]
what does closed me sorry lol

Darren Johnson

**Comment by whitesoup12** [comment]
It's been done. :)

**Comment by BulbsOnBenito** [comment]
YAY! how does it work?! omgosh yay

Darren Johnson

**Comment by whitesoup12** [comment]
https://github.com/whitesoup12/remote-falcon-tracker/wiki/Remote-Falcon-Wiki#play-sequence
