### ISSUE TITLE
Fire FPP Command from Remote Falcon

### ISSUE THREAD

**Issue by robbiet76** [whitesoup12/remote-falcon-tracker#95]
This is a request for an enhancement.  I would like to have the ability to fire an FPP command via my remote falcon page.  

For my specific use case, I'd like to add a button on my page that allows viewers to turn on outdoor speakers at my display if they are standing outside or unable to tune into my radio station.  I can trigger this today in FPP using an MQTT command to my home automation system, but I need to get the control to the viewers in Remote Falcon.

I would think this would open up all kinds of possibilities for making our displays more interactive as you could give users all kinds of control over display elements.

**Comment by whitesoup12** [comment]
This is now part of FPP plugin version 6.3.0
