### ISSUE TITLE
Keep Sequence list alphabetically in voting mode

### ISSUE THREAD

**Issue by DougD-Xlights** [whitesoup12/remote-falcon-tracker#99]
It would be helpful to keep the viewer sequence list alphabetical while in voting mode. That way, the viewers can find the sequence they wish to vote for easier. Obviously any sequence vote on already would be at the top but alphabetical after that.

**Comment by whitesoup12** [comment]
Sequences in voting mode will now reflect the custom ordering from the Sequences tab of the Control Panel, with highest voted sequences on the top.
